
model_params:
  n_embd: 512
  n_layer: 12
  n_head : 16
  embd_pdrop : 0.1
  resid_pdrop : 0.1
  attn_pdrop : 0.1
  model_type : 'bert'
  vocab_size : 22      # 20 amino acids + 1 for unknown aa and + 1 for mask token
  block_size : 90      # 246 # min length of any given entry in the dataset
  mask_prob : 0.15
  weight_decay : 0.1
  learning_rate : 0.0001
  lr_gamma: 0.9985     # for exponential learning rate decay
  betas : [0.9, 0.95]
  accelerator: 'gpu'
  devices: 2
  batch_size: 128
  num_workers: 20
  grad_norm_clip : 1.0
  num_epochs : 10
  checkpoint_every_n_train_steps : 100
  save_top_k : 1
  monitor: 'loss'
  mode: 'min'
  log_dir: './lightning_logs/'
  log_every_nsteps: 100

  seed : 3407

